const CONFIG = {
  // 博客名称
  TYPOGRAPHY_BLOG_NAME: process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME || 'typography',
  TYPOGRAPHY_BLOG_NAME_EN: process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME_EN || 'Typography',

  // 不显示广告
  TYPOGRAPHY_POST_AD_ENABLE: false,

  // 不显示封面
  TYPOGRAPHY_POST_COVER_ENABLE: false,

  // 显示推荐文章
  TYPOGRAPHY_ARTICLE_RECOMMEND_POSTS: true,

  // 菜单配置
  TYPOGRAPHY_MENU_CATEGORY: true,
  TYPOGRAPHY_MENU_TAG: true,
  TYPOGRAPHY_MENU_ARCHIVE: true,
}
export default CONFIG
